version: "3.9"

services:
  mysql:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spin
      MYSQL_DATABASE: spin_dev
      MYSQL_USER: spin
      MYSQL_PASSWORD: spin
  redis:
    image: redis:7.0.8-alpine3.17
    ports:
      - "6379:6379"
    restart: always

  e2e-tests:
    depends_on:
      - mysql
    image: spin-e2e-tests
    entrypoint: cargo test spinup_tests --features new-e2e-tests --no-fail-fast -- --nocapture
    volumes:
      - ./target/release/spin:/usr/local/bin/spin

volumes:
  db_data: {}
