# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Rust
on:
  push:
    branches: [main]
    # Also run on tag pushes, as the release.yml doesn't currently run tests
    tags: ["v*"]
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "README.md"
env:
  CARGO_TERM_COLOR: always
jobs:
  build-rust:
    name: Build Spin
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              sleep: "2",
              os: "ubuntu-latest",
              extension: "",
              # We have this enabled for releases, so we should test it.
              extraArgs: "--features openssl/vendored",
            }
          - {
              sleep: "5",
              os: "macos-latest",
              extension: "",
              extraArgs: "",
            }
          - {
              sleep: "10",
              os: "windows-latest",
              extension: ".exe",
              extraArgs: "",
            }
    steps:
      - run: sleep ${{ matrix.config.sleep }}
      - run: echo "finishing run on ${{  runner.os }}"

  fast-ci:
    name: Build Spin
    runs-on: ubuntu-latest
    needs: [build-rust]
    steps:
      - run: echo "running downstream job"
